### ISSUE TITLE
Mudar o formato dos arquivos para download(das aulas).

### ISSUE THREAD

**Issue by federfelipe** [alerj/parlamentojuvenil#100]
É interessante colocar os arquivos das aulas em PDF. 
Ele está no formato odp e abre para edição, em vez de abrir direto na apresentação. O Pdf também impede diferenças nas visualizações(arquivo feito no libre e visualizado no power pode conter diferenças, por exemplo)

**Comment by antonioribeiro** [comment]
Fixed in https://github.com/alerj/parlamentojuvenil/pull/102
