### ISSUE TITLE
Erro alunos com mais de 17 anos se inscrevendo

### ISSUE THREAD

**Issue by orlandovinicius1987** [alerj/parlamentojuvenil#208]
Há alunos fora da data de nascimento prevista se inscrevendo.

**Comment by BMasquio** [comment]
Eu não sei se #209 resolve totalmente o problema.

O login do seeduc pode já ter sido criado em algum ano anterior. Aquela tela de formulário só aparece quando o usuário não está associado a nenhum estudante. Ou seja, se uma pessoa estava na idade de se inscrever em 2016 e não em 2018 e ela se inscreveu em 2016, o estudante já está associado ao login dela. Então, ao tentar se inscrever em 2018, não ia passar por essa tela e ela ia direto para a inscrição, que, pelo que observei, não valida mais a idade.

**Comment by BMasquio** [comment]
Fiz uma mudança, restringindo mais duas rotas ao middleware de check-student-age. Uma rota é a abertura do form de dados (CPF, endereço etc) e a outra é a rota de envio desse form.

@antonioribeiro , dá uma olhada aí e vê se as nossas soluções(unidas ou não) ajudam a resolver.

**Comment by BMasquio** [comment]
OBS: Nos meus testes, funcionou

STUDENT_BIRTHDATE_START=2001-12-01
STUDENT_BIRTHDATE_END=2005-11-23

2001-11-30 NÃO PERMITIU
2001-12-02 PERMITIU
2005-11-22 PERMITIU
2005-11-24 NÃO PERMITIU

**Comment by BMasquio** [comment]
Fechando a issue pois foi resolvido
