### ISSUE TITLE
2019: Texto para o banner da capacitação

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/parlamentojuvenil#223]
“Prezados (as) Parlamentares Juvenis da Edição de 2019,
No decorrer das próximas duas semanas vocês terão a oportunidade de ampliar seus conhecimentos aprendendo um pouco sobre técnica legislativa, instrumento essencial para orientá-los (as) na construção do seus projetos de lei. 
A capacitação on-line é uma atividade fundamental para aprimorar os seus desempenhos na etapa de capacitação presencial.
A capacitação on-line será dividida em dois módulos semanais compostos de videoaula e questionário.
 Para conclusão de cada módulo é necessário que vocês assistam a videoaula e preencham o formulário final que os habilitará a realizar o próximo módulo.

(texto do Antônio sobre acesso ao link)

Vocês estão prontos para essa nova etapa? Clique no link abaixo e sucesso!”

**Comment by BMasquio** [comment]
Fechando a issue pois mudou o ano da edição
